### ISSUE TITLE
Refactor Opportunities - use config file for constants (addresses)

### ISSUE THREAD

**Issue by antoncoding** [opynfinance/Gamma-Bots#1]
We can use a config file for all the addresses, e.g. `relayerAddress`, `addressbookAddress`, `chainlinkAggregatorAddress` to minimize the overhead.

**Comment by haythemsellami** [comment]
What do u mean by config file ?

**Comment by antoncoding** [comment]
instead of having addresses hardcoded in your script, you can use a `config.js` to export all addresses.  (just like you did for the gamma migration scripts I think that's a good way to manage things)
